/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bsuu6aAij40
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Taviraj } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    (<div
      className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20">
      <div className="flex items-center justify-between mb-8">
        <h1
          className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-100">Movie Search</h1>
        <Button className="flex items-center gap-2" variant="outline">
          <RefreshCwIcon className="w-5 h-5" />
          Reset Search
        </Button>
      </div>
      <div className="mb-8">
        <Input className="w-full max-w-md" placeholder="Search for a movie..." />
      </div>
      <div
        className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">The Shawshank Redemption</h3>
              <div
                className="bg-green-500 text-white px-2 py-1 rounded-md text-xs font-medium">Drama</div>
            </div>
            <p className="text-gray-500 dark:text-gray-400">Starring: Tim Robbins, Morgan Freeman</p>
            <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
              Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of
              common decency.
            </p>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1">
                <StarIcon className="w-5 h-5 text-yellow-500" />
                <span className="font-medium">9.3</span>
              </div>
              <div
                className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-md text-xs font-medium text-gray-500 dark:text-gray-400">
                1994
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">Inception</h3>
              <div
                className="bg-blue-500 text-white px-2 py-1 rounded-md text-xs font-medium">Sci-Fi</div>
            </div>
            <p className="text-gray-500 dark:text-gray-400">Starring: Leonardo DiCaprio, Ellen Page</p>
            <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
              A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task
              of planting an idea in the mind of a CEO.
            </p>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1">
                <StarIcon className="w-5 h-5 text-yellow-500" />
                <span className="font-medium">8.8</span>
              </div>
              <div
                className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-md text-xs font-medium text-gray-500 dark:text-gray-400">
                2010
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">The Dark Knight</h3>
              <div
                className="bg-red-500 text-white px-2 py-1 rounded-md text-xs font-medium">Action</div>
            </div>
            <p className="text-gray-500 dark:text-gray-400">Starring: Christian Bale, Heath Ledger</p>
            <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
              When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must
              come to terms with one of the greatest psychological tests of his ability to fight injustice.
            </p>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1">
                <StarIcon className="w-5 h-5 text-yellow-500" />
                <span className="font-medium">9.0</span>
              </div>
              <div
                className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-md text-xs font-medium text-gray-500 dark:text-gray-400">
                2008
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">Forrest Gump</h3>
              <div
                className="bg-yellow-500 text-white px-2 py-1 rounded-md text-xs font-medium">Drama</div>
            </div>
            <p className="text-gray-500 dark:text-gray-400">Starring: Tom Hanks, Robin Wright</p>
            <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
              The story of a man who witnesses and influences several major historical events in the United States from
              the late 1950s to the 1990s.
            </p>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1">
                <StarIcon className="w-5 h-5 text-yellow-500" />
                <span className="font-medium">8.8</span>
              </div>
              <div
                className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-md text-xs font-medium text-gray-500 dark:text-gray-400">
                1994
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}

function RefreshCwIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
